<?php

namespace EvolutionCMS\Installer\Install;

use Illuminate\Database\Seeder;

class SystemEventnamesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('system_eventnames')->delete();

        \DB::table('system_eventnames')->insert([
            0   => ['name' => 'OnAfterLoadDocumentObject', 'service' => '5', 'groupname' => '',],
            1   => ['name' => 'OnAfterMoveDocument', 'service' => '1', 'groupname' => 'Documents',],
            2   => ['name' => 'OnBeforeCacheUpdate', 'service' => '4', 'groupname' => '',],
            3   => ['name' => 'OnBeforeChunkFormDelete', 'service' => '1', 'groupname' => 'Chunks',],
            4   => ['name' => 'OnBeforeChunkFormSave', 'service' => '1', 'groupname' => 'Chunks',],
            5   => ['name' => 'OnBeforeDocDuplicate', 'service' => '1', 'groupname' => 'Documents',],
            6   => ['name' => 'OnBeforeDocFormDelete', 'service' => '1', 'groupname' => 'Documents',],
            7   => ['name' => 'OnBeforeDocFormSave', 'service' => '1', 'groupname' => 'Documents',],
            8   => ['name' => 'OnBeforeEmptyTrash', 'service' => '1', 'groupname' => 'Documents',],
            9   => ['name' => 'OnBeforeFileBrowserCopy', 'service' => '1', 'groupname' => 'File Browser Events',],
            10  => ['name' => 'OnBeforeFileBrowserDelete', 'service' => '1', 'groupname' => 'File Browser Events',],
            11  => ['name' => 'OnBeforeFileBrowserMove', 'service' => '1', 'groupname' => 'File Browser Events',],
            12  => ['name' => 'OnBeforeFileBrowserRename', 'service' => '1', 'groupname' => 'File Browser Events',],
            13  => ['name' => 'OnBeforeFileBrowserUpload', 'service' => '1', 'groupname' => 'File Browser Events',],
            14  => ['name' => 'OnBeforeLoadDocumentObject', 'service' => '5', 'groupname' => '',],
            15  => ['name' => 'OnBeforeLoadExtension', 'service' => '5', 'groupname' => '',],
            16  => ['name' => 'OnBeforeManagerPageInit', 'service' => '2', 'groupname' => '',],
            17  => ['name' => 'OnBeforeMinifyCss', 'service' => '1', 'groupname' => '',],
            18  => ['name' => 'OnBeforeModFormDelete', 'service' => '1', 'groupname' => 'Modules',],
            19  => ['name' => 'OnBeforeModFormSave', 'service' => '1', 'groupname' => 'Modules',],
            20  => ['name' => 'OnBeforeMoveDocument', 'service' => '1', 'groupname' => 'Documents',],
            21  => ['name' => 'OnBeforeParseParams', 'service' => '5', 'groupname' => '',],
            22  => ['name' => 'OnBeforePluginFormDelete', 'service' => '1', 'groupname' => 'Plugins',],
            23  => ['name' => 'OnBeforePluginFormSave', 'service' => '1', 'groupname' => 'Plugins',],
            24  => ['name' => 'OnBeforeSaveWebPageCache', 'service' => '4', 'groupname' => '',],
            25  => ['name' => 'OnBeforeSnipFormDelete', 'service' => '1', 'groupname' => 'Snippets',],
            26  => ['name' => 'OnBeforeSnipFormSave', 'service' => '1', 'groupname' => 'Snippets',],
            27  => ['name' => 'OnBeforeTempFormDelete', 'service' => '1', 'groupname' => 'Templates',],
            28  => ['name' => 'OnBeforeTempFormSave', 'service' => '1', 'groupname' => 'Templates',],
            29  => ['name' => 'OnBeforeTVFormDelete', 'service' => '1', 'groupname' => 'Template Variables',],
            30  => ['name' => 'OnBeforeTVFormSave', 'service' => '1', 'groupname' => 'Template Variables',],
            31  => ['name' => 'OnBeforeUserDelete', 'service' => '1', 'groupname' => 'Users',],
            32  => ['name' => 'OnBeforeUserLogin', 'service' => '1', 'groupname' => 'Users',],
            33  => ['name' => 'OnBeforeUserLogout', 'service' => '1', 'groupname' => 'Users',],
            34  => ['name' => 'OnBeforeUserSave', 'service' => '1', 'groupname' => 'Users',],
            35  => ['name' => 'OnCacheUpdate', 'service' => '4', 'groupname' => '',],
            36  => ['name' => 'OnChunkFormDelete', 'service' => '1', 'groupname' => 'Chunks',],
            37  => ['name' => 'OnChunkFormPrerender', 'service' => '1', 'groupname' => 'Chunks',],
            38  => ['name' => 'OnChunkFormRender', 'service' => '1', 'groupname' => 'Chunks',],
            39  => ['name' => 'OnChunkFormSave', 'service' => '1', 'groupname' => 'Chunks',],
            40  => ['name' => 'OnCreateDocGroup', 'service' => '1', 'groupname' => 'Documents',],
            41  => ['name' => 'OnDocDuplicate', 'service' => '1', 'groupname' => 'Documents',],
            42  => ['name' => 'OnDocFormDelete', 'service' => '1', 'groupname' => 'Documents',],
            43  => ['name' => 'OnDocFormPrerender', 'service' => '1', 'groupname' => 'Documents',],
            44  => ['name' => 'OnDocFormRender', 'service' => '1', 'groupname' => 'Documents',],
            45  => ['name' => 'OnDocFormSave', 'service' => '1', 'groupname' => 'Documents',],
            46  => ['name' => 'OnDocFormTemplateRender', 'service' => '1', 'groupname' => 'Documents',],
            47  => ['name' => 'OnDocFormUnDelete', 'service' => '1', 'groupname' => 'Documents',],
            48  => ['name' => 'OnDocPublished', 'service' => '5', 'groupname' => '',],
            49  => ['name' => 'OnDocUnPublished', 'service' => '5', 'groupname' => '',],
            50  => ['name' => 'OnEmptyTrash', 'service' => '1', 'groupname' => 'Documents',],
            51  => ['name' => 'OnFileBrowserCopy', 'service' => '1', 'groupname' => 'File Browser Events',],
            52  => ['name' => 'OnFileBrowserDelete', 'service' => '1', 'groupname' => 'File Browser Events',],
            53  => ['name' => 'OnFileBrowserInit', 'service' => '1', 'groupname' => 'File Browser Events',],
            54  => ['name' => 'OnFileBrowserMove', 'service' => '1', 'groupname' => 'File Browser Events',],
            55  => ['name' => 'OnFileBrowserRename', 'service' => '1', 'groupname' => 'File Browser Events',],
            56  => ['name' => 'OnFileBrowserUpload', 'service' => '1', 'groupname' => 'File Browser Events',],
            57  => ['name' => 'OnFileManagerSettingsRender', 'service' => '1', 'groupname' => 'System Settings',],
            58  => ['name' => 'OnFileManagerUpload', 'service' => '1', 'groupname' => '',],
            59  => ['name' => 'OnFriendlyURLSettingsRender', 'service' => '1', 'groupname' => 'System Settings',],
            60  => ['name' => 'OnInterfaceSettingsRender', 'service' => '1', 'groupname' => 'System Settings',],
            61  => ['name' => 'OnLoadDocumentObject', 'service' => '5', 'groupname' => '',],
            62  => ['name' => 'OnLoadSettings', 'service' => '1', 'groupname' => 'System Settings',],
            63  => ['name' => 'OnLoadWebDocument', 'service' => '5', 'groupname' => '',],
            64  => ['name' => 'OnLoadWebPageCache', 'service' => '4', 'groupname' => '',],
            65  => ['name' => 'OnLogEvent', 'service' => '1', 'groupname' => 'Log Event',],
            66  => ['name' => 'OnLogPageHit', 'service' => '5', 'groupname' => '',],
            67  => ['name' => 'OnMakeDocUrl', 'service' => '5', 'groupname' => '',],
            68  => ['name' => 'OnMakePageCacheKey', 'service' => '4', 'groupname' => '',],
            69  => ['name' => 'OnManagerFrameLoader', 'service' => '2', 'groupname' => '',],
            70  => ['name' => 'OnManagerLoginFormPrerender', 'service' => '2', 'groupname' => '',],
            71  => ['name' => 'OnManagerLoginFormRender', 'service' => '2', 'groupname' => '',],
            72  => ['name' => 'OnManagerMainFrameHeaderHTMLBlock', 'service' => '2', 'groupname' => '',],
            73  => ['name' => 'OnManagerMenuPrerender', 'service' => '2', 'groupname' => '',],
            74  => ['name' => 'OnManagerNodePrerender', 'service' => '2', 'groupname' => '',],
            75  => ['name' => 'OnManagerNodeRender', 'service' => '2', 'groupname' => '',],
            76  => ['name' => 'OnManagerPageInit', 'service' => '2', 'groupname' => '',],
            77  => ['name' => 'OnManagerPreFrameLoader', 'service' => '2', 'groupname' => '',],
            78  => ['name' => 'OnManagerTopPrerender', 'service' => '2', 'groupname' => '',],
            79  => ['name' => 'OnManagerTreeInit', 'service' => '2', 'groupname' => '',],
            80  => ['name' => 'OnManagerTreePrerender', 'service' => '2', 'groupname' => '',],
            81  => ['name' => 'OnManagerTreeRender', 'service' => '2', 'groupname' => '',],
            82  => ['name' => 'OnManagerWelcomeHome', 'service' => '2', 'groupname' => '',],
            83  => ['name' => 'OnManagerWelcomePrerender', 'service' => '2', 'groupname' => '',],
            84  => ['name' => 'OnManagerWelcomeRender', 'service' => '2', 'groupname' => '',],
            85  => ['name' => 'OnMiscSettingsRender', 'service' => '1', 'groupname' => 'System Settings',],
            86  => ['name' => 'OnModFormDelete', 'service' => '1', 'groupname' => 'Modules',],
            87  => ['name' => 'OnModFormPrerender', 'service' => '1', 'groupname' => 'Modules',],
            88  => ['name' => 'OnModFormRender', 'service' => '1', 'groupname' => 'Modules',],
            89  => ['name' => 'OnModFormSave', 'service' => '1', 'groupname' => 'Modules',],
            90  => ['name' => 'OnPageNotFound', 'service' => '1', 'groupname' => '',],
            91  => ['name' => 'OnPageUnauthorized', 'service' => '1', 'groupname' => '',],
            92  => ['name' => 'OnParseDocument', 'service' => '5', 'groupname' => '',],
            93  => ['name' => 'OnParseProperties', 'service' => '5', 'groupname' => '',],
            94  => ['name' => 'OnPluginFormDelete', 'service' => '1', 'groupname' => 'Plugins',],
            95  => ['name' => 'OnPluginFormPrerender', 'service' => '1', 'groupname' => 'Plugins',],
            96  => ['name' => 'OnPluginFormRender', 'service' => '1', 'groupname' => 'Plugins',],
            97  => ['name' => 'OnPluginFormSave', 'service' => '1', 'groupname' => 'Plugins',],
            98  => ['name' => 'OnRichTextEditorInit', 'service' => '1', 'groupname' => 'RichText Editor',],
            99  => ['name' => 'OnRichTextEditorRegister', 'service' => '1', 'groupname' => 'RichText Editor',],
            100 => ['name' => 'OnSecuritySettingsRender', 'service' => '1', 'groupname' => 'System Settings',],
            101 => ['name' => 'OnSiteRefresh', 'service' => '1', 'groupname' => '',],
            102 => ['name' => 'OnSiteSettingsRender', 'service' => '1', 'groupname' => 'System Settings',],
            103 => ['name' => 'OnSnipFormDelete', 'service' => '1', 'groupname' => 'Snippets',],
            104 => ['name' => 'OnSnipFormPrerender', 'service' => '1', 'groupname' => 'Snippets',],
            105 => ['name' => 'OnSnipFormRender', 'service' => '1', 'groupname' => 'Snippets',],
            106 => ['name' => 'OnSnipFormSave', 'service' => '1', 'groupname' => 'Snippets',],
            107 => ['name' => 'OnStripAlias', 'service' => '1', 'groupname' => 'Documents',],
            108 => ['name' => 'OnTempFormDelete', 'service' => '1', 'groupname' => 'Templates',],
            109 => ['name' => 'OnTempFormPrerender', 'service' => '1', 'groupname' => 'Templates',],
            110 => ['name' => 'OnTempFormRender', 'service' => '1', 'groupname' => 'Templates',],
            111 => ['name' => 'OnTempFormSave', 'service' => '1', 'groupname' => 'Templates',],
            112 => ['name' => 'OnTVFormDelete', 'service' => '1', 'groupname' => 'Template Variables',],
            113 => ['name' => 'OnTVFormPrerender', 'service' => '1', 'groupname' => 'Template Variables',],
            114 => ['name' => 'OnTVFormRender', 'service' => '1', 'groupname' => 'Template Variables',],
            115 => ['name' => 'OnTVFormSave', 'service' => '1', 'groupname' => 'Template Variables',],
            116 => ['name' => 'OnUserAuthentication', 'service' => '1', 'groupname' => 'Users',],
            117 => ['name' => 'OnUserChangePassword', 'service' => '1', 'groupname' => 'Users',],
            118 => ['name' => 'OnUserCreateGroup', 'service' => '1', 'groupname' => 'Users',],
            119 => ['name' => 'OnUserDelete', 'service' => '1', 'groupname' => 'Users',],
            120 => ['name' => 'OnUserFormPrerender', 'service' => '1', 'groupname' => 'Users',],
            121 => ['name' => 'OnUserFormRender', 'service' => '1', 'groupname' => 'Users',],
            122 => ['name' => 'OnUserLogin', 'service' => '1', 'groupname' => 'Users',],
            123 => ['name' => 'OnUserLogout', 'service' => '1', 'groupname' => 'Users',],
            124 => ['name' => 'OnUserSave', 'service' => '1', 'groupname' => 'Users',],
            125 => ['name' => 'OnUserSettingsRender', 'service' => '1', 'groupname' => 'System Settings',],
            126 => ['name' => 'OnWebPageComplete', 'service' => '5', 'groupname' => '',],
            127 => ['name' => 'OnWebPageInit', 'service' => '5', 'groupname' => '',],
            128 => ['name' => 'OnWebPagePrerender', 'service' => '5', 'groupname' => '',],
        ]);
    }
}
