<?php

namespace EvolutionCMS\Installer\Install;

use Illuminate\Database\Seeder;

class SystemEventnamesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('system_eventnames')->delete();

        \DB::table('system_eventnames')->insert([
            ['name' => 'OnAfterLoadDocumentObject', 'service' => '5', 'groupname' => '',],
            ['name' => 'OnAfterMoveDocument', 'service' => '1', 'groupname' => 'Documents',],
            ['name' => 'OnBeforeCacheUpdate', 'service' => '4', 'groupname' => '',],
            ['name' => 'OnBeforeChunkFormDelete', 'service' => '1', 'groupname' => 'Chunks',],
            ['name' => 'OnBeforeChunkFormSave', 'service' => '1', 'groupname' => 'Chunks',],
            ['name' => 'OnBeforeDocDuplicate', 'service' => '1', 'groupname' => 'Documents',],
            ['name' => 'OnBeforeDocFormDelete', 'service' => '1', 'groupname' => 'Documents',],
            ['name' => 'OnBeforeDocFormSave', 'service' => '1', 'groupname' => 'Documents',],
            ['name' => 'OnBeforeEmptyTrash', 'service' => '1', 'groupname' => 'Documents',],
            ['name' => 'OnBeforeFileBrowserCopy', 'service' => '1', 'groupname' => 'File Browser Events',],
            ['name' => 'OnBeforeFileBrowserDelete', 'service' => '1', 'groupname' => 'File Browser Events',],
            ['name' => 'OnBeforeFileBrowserMove', 'service' => '1', 'groupname' => 'File Browser Events',],
            ['name' => 'OnBeforeFileBrowserRename', 'service' => '1', 'groupname' => 'File Browser Events',],
            ['name' => 'OnBeforeFileBrowserUpload', 'service' => '1', 'groupname' => 'File Browser Events',],
            ['name' => 'OnBeforeLoadDocumentObject', 'service' => '5', 'groupname' => '',],
            ['name' => 'OnBeforeLoadExtension', 'service' => '5', 'groupname' => '',],
            ['name' => 'OnBeforeManagerPageInit', 'service' => '2', 'groupname' => '',],
            ['name' => 'OnBeforeMinifyCss', 'service' => '1', 'groupname' => '',],
            ['name' => 'OnBeforeModFormDelete', 'service' => '1', 'groupname' => 'Modules',],
            ['name' => 'OnBeforeModFormSave', 'service' => '1', 'groupname' => 'Modules',],
            ['name' => 'OnBeforeMoveDocument', 'service' => '1', 'groupname' => 'Documents',],
            ['name' => 'OnBeforeParseParams', 'service' => '5', 'groupname' => '',],
            ['name' => 'OnBeforePluginFormDelete', 'service' => '1', 'groupname' => 'Plugins',],
            ['name' => 'OnBeforePluginFormSave', 'service' => '1', 'groupname' => 'Plugins',],
            ['name' => 'OnBeforeSaveWebPageCache', 'service' => '4', 'groupname' => '',],
            ['name' => 'OnBeforeSnipFormDelete', 'service' => '1', 'groupname' => 'Snippets',],
            ['name' => 'OnBeforeSnipFormSave', 'service' => '1', 'groupname' => 'Snippets',],
            ['name' => 'OnBeforeTempFormDelete', 'service' => '1', 'groupname' => 'Templates',],
            ['name' => 'OnBeforeTempFormSave', 'service' => '1', 'groupname' => 'Templates',],
            ['name' => 'OnBeforeTVFormDelete', 'service' => '1', 'groupname' => 'Template Variables',],
            ['name' => 'OnBeforeTVFormSave', 'service' => '1', 'groupname' => 'Template Variables',],
            ['name' => 'OnBeforeUserDelete', 'service' => '1', 'groupname' => 'Users',],
            ['name' => 'OnBeforeUserLogin', 'service' => '1', 'groupname' => 'Users',],
            ['name' => 'OnBeforeUserLogout', 'service' => '1', 'groupname' => 'Users',],
            ['name' => 'OnBeforeUserSave', 'service' => '1', 'groupname' => 'Users',],
            ['name' => 'OnCacheUpdate', 'service' => '4', 'groupname' => '',],
            ['name' => 'OnChunkFormDelete', 'service' => '1', 'groupname' => 'Chunks',],
            ['name' => 'OnChunkFormPrerender', 'service' => '1', 'groupname' => 'Chunks',],
            ['name' => 'OnChunkFormRender', 'service' => '1', 'groupname' => 'Chunks',],
            ['name' => 'OnChunkFormSave', 'service' => '1', 'groupname' => 'Chunks',],
            ['name' => 'OnCreateDocGroup', 'service' => '1', 'groupname' => 'Documents',],
            ['name' => 'OnDocDuplicate', 'service' => '1', 'groupname' => 'Documents',],
            ['name' => 'OnDocFormDelete', 'service' => '1', 'groupname' => 'Documents',],
            ['name' => 'OnDocFormPrerender', 'service' => '1', 'groupname' => 'Documents',],
            ['name' => 'OnDocFormRender', 'service' => '1', 'groupname' => 'Documents',],
            ['name' => 'OnDocFormSave', 'service' => '1', 'groupname' => 'Documents',],
            ['name' => 'OnDocFormTemplateRender', 'service' => '1', 'groupname' => 'Documents',],
            ['name' => 'OnDocFormUnDelete', 'service' => '1', 'groupname' => 'Documents',],
            ['name' => 'OnDocPublished', 'service' => '5', 'groupname' => '',],
            ['name' => 'OnDocUnPublished', 'service' => '5', 'groupname' => '',],
            ['name' => 'OnEmptyTrash', 'service' => '1', 'groupname' => 'Documents',],
            ['name' => 'OnFileBrowserCopy', 'service' => '1', 'groupname' => 'File Browser Events',],
            ['name' => 'OnFileBrowserDelete', 'service' => '1', 'groupname' => 'File Browser Events',],
            ['name' => 'OnFileBrowserInit', 'service' => '1', 'groupname' => 'File Browser Events',],
            ['name' => 'OnFileBrowserMove', 'service' => '1', 'groupname' => 'File Browser Events',],
            ['name' => 'OnFileBrowserRename', 'service' => '1', 'groupname' => 'File Browser Events',],
            ['name' => 'OnFileBrowserUpload', 'service' => '1', 'groupname' => 'File Browser Events',],
            ['name' => 'OnFileManagerSettingsRender', 'service' => '1', 'groupname' => 'System Settings',],
            ['name' => 'OnFileManagerUpload', 'service' => '1', 'groupname' => '',],
            ['name' => 'OnFriendlyURLSettingsRender', 'service' => '1', 'groupname' => 'System Settings',],
            ['name' => 'OnInterfaceSettingsRender', 'service' => '1', 'groupname' => 'System Settings',],
            ['name' => 'OnLoadDocumentObject', 'service' => '5', 'groupname' => '',],
            ['name' => 'OnLoadSettings', 'service' => '1', 'groupname' => 'System Settings',],
            ['name' => 'OnLoadWebDocument', 'service' => '5', 'groupname' => '',],
            ['name' => 'OnLoadWebPageCache', 'service' => '4', 'groupname' => '',],
            ['name' => 'OnLogEvent', 'service' => '1', 'groupname' => 'Log Event',],
            ['name' => 'OnLogPageHit', 'service' => '5', 'groupname' => '',],
            ['name' => 'OnMakeDocUrl', 'service' => '5', 'groupname' => '',],
            ['name' => 'OnMakePageCacheKey', 'service' => '4', 'groupname' => '',],
            ['name' => 'OnManagerFrameLoader', 'service' => '2', 'groupname' => '',],
            ['name' => 'OnManagerLoginFormPrerender', 'service' => '2', 'groupname' => '',],
            ['name' => 'OnManagerLoginFormRender', 'service' => '2', 'groupname' => '',],
            ['name' => 'OnManagerMainFrameHeaderHTMLBlock', 'service' => '2', 'groupname' => '',],
            ['name' => 'OnManagerMenuPrerender', 'service' => '2', 'groupname' => '',],
            ['name' => 'OnManagerNodePrerender', 'service' => '2', 'groupname' => '',],
            ['name' => 'OnManagerNodeRender', 'service' => '2', 'groupname' => '',],
            ['name' => 'OnManagerPageInit', 'service' => '2', 'groupname' => '',],
            ['name' => 'OnManagerPreFrameLoader', 'service' => '2', 'groupname' => '',],
            ['name' => 'OnManagerTopPrerender', 'service' => '2', 'groupname' => '',],
            ['name' => 'OnManagerTreeInit', 'service' => '2', 'groupname' => '',],
            ['name' => 'OnManagerTreePrerender', 'service' => '2', 'groupname' => '',],
            ['name' => 'OnManagerTreeRender', 'service' => '2', 'groupname' => '',],
            ['name' => 'OnManagerWelcomeHome', 'service' => '2', 'groupname' => '',],
            ['name' => 'OnManagerWelcomePrerender', 'service' => '2', 'groupname' => '',],
            ['name' => 'OnManagerWelcomeRender', 'service' => '2', 'groupname' => '',],
            ['name' => 'OnMiscSettingsRender', 'service' => '1', 'groupname' => 'System Settings',],
            ['name' => 'OnModFormDelete', 'service' => '1', 'groupname' => 'Modules',],
            ['name' => 'OnModFormPrerender', 'service' => '1', 'groupname' => 'Modules',],
            ['name' => 'OnModFormRender', 'service' => '1', 'groupname' => 'Modules',],
            ['name' => 'OnModFormSave', 'service' => '1', 'groupname' => 'Modules',],
            ['name' => 'OnPageNotFound', 'service' => '1', 'groupname' => '',],
            ['name' => 'OnPageUnauthorized', 'service' => '1', 'groupname' => '',],
            ['name' => 'OnParseDocument', 'service' => '5', 'groupname' => '',],
            ['name' => 'OnParseProperties', 'service' => '5', 'groupname' => '',],
            ['name' => 'OnPluginFormDelete', 'service' => '1', 'groupname' => 'Plugins',],
            ['name' => 'OnPluginFormPrerender', 'service' => '1', 'groupname' => 'Plugins',],
            ['name' => 'OnPluginFormRender', 'service' => '1', 'groupname' => 'Plugins',],
            ['name' => 'OnPluginFormSave', 'service' => '1', 'groupname' => 'Plugins',],
            ['name' => 'OnRichTextEditorInit', 'service' => '1', 'groupname' => 'RichText Editor',],
            ['name' => 'OnRichTextEditorRegister', 'service' => '1', 'groupname' => 'RichText Editor',],
            ['name' => 'OnSecuritySettingsRender', 'service' => '1', 'groupname' => 'System Settings',],
            ['name' => 'OnSiteRefresh', 'service' => '1', 'groupname' => '',],
            ['name' => 'OnSiteSettingsRender', 'service' => '1', 'groupname' => 'System Settings',],
            ['name' => 'OnSnipFormDelete', 'service' => '1', 'groupname' => 'Snippets',],
            ['name' => 'OnSnipFormPrerender', 'service' => '1', 'groupname' => 'Snippets',],
            ['name' => 'OnSnipFormRender', 'service' => '1', 'groupname' => 'Snippets',],
            ['name' => 'OnSnipFormSave', 'service' => '1', 'groupname' => 'Snippets',],
            ['name' => 'OnStripAlias', 'service' => '1', 'groupname' => 'Documents',],
            ['name' => 'OnTempFormDelete', 'service' => '1', 'groupname' => 'Templates',],
            ['name' => 'OnTempFormPrerender', 'service' => '1', 'groupname' => 'Templates',],
            ['name' => 'OnTempFormRender', 'service' => '1', 'groupname' => 'Templates',],
            ['name' => 'OnTempFormSave', 'service' => '1', 'groupname' => 'Templates',],
            ['name' => 'OnTVFormDelete', 'service' => '1', 'groupname' => 'Template Variables',],
            ['name' => 'OnTVFormPrerender', 'service' => '1', 'groupname' => 'Template Variables',],
            ['name' => 'OnTVFormRender', 'service' => '1', 'groupname' => 'Template Variables',],
            ['name' => 'OnTVFormSave', 'service' => '1', 'groupname' => 'Template Variables',],
            ['name' => 'OnUserAuthentication', 'service' => '1', 'groupname' => 'Users',],
            ['name' => 'OnUserChangePassword', 'service' => '1', 'groupname' => 'Users',],
            ['name' => 'OnUserCreateGroup', 'service' => '1', 'groupname' => 'Users',],
            ['name' => 'OnUserDelete', 'service' => '1', 'groupname' => 'Users',],
            ['name' => 'OnUserFormPrerender', 'service' => '1', 'groupname' => 'Users',],
            ['name' => 'OnUserFormRender', 'service' => '1', 'groupname' => 'Users',],
            ['name' => 'OnUserLogin', 'service' => '1', 'groupname' => 'Users',],
            ['name' => 'OnUserLogout', 'service' => '1', 'groupname' => 'Users',],
            ['name' => 'OnUserSave', 'service' => '1', 'groupname' => 'Users',],
            ['name' => 'OnUserSettingsRender', 'service' => '1', 'groupname' => 'System Settings',],
            ['name' => 'OnWebPageComplete', 'service' => '5', 'groupname' => '',],
            ['name' => 'OnWebPageInit', 'service' => '5', 'groupname' => '',],
            ['name' => 'OnWebPagePrerender', 'service' => '5', 'groupname' => '',],
            ['name' => 'OnBeforeMailSend', 'service' => '1', 'groupname' => '',],
        ]);
    }
}
