name: Feature request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: Quick summary what's this feature request about.
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is it needed?
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: suggested
    attributes:
      label: Suggested solution(s)
      placeholder: A clear and concise description of what you want to happen.
  - type: textarea
    id: related
    attributes:
      label: Related issue(s)/PR(s)
      placeholder: Let us know if this is related to any issue/pull request.
