<?php

use EvolutionCMS\Facades\ManagerTheme;

?>
<form id="category-edit-form" action="<?= $view->get('url'); ?>" method="post">
    <?= csrf_field() ?>
    <input name="<?= $view->get('request_key'); ?>[edit][submit]" type="hidden" value="1"/>
    <div class="form-group">
        <a class="btn btn-success btn-sm" href="javascript:;"
           onclick="document.getElementById('category-edit-form').submit();return false;"><i
                    class="<?= ManagerTheme::getStyle('icon_refresh') ?>"></i>
            <?= $view->txt('cm_update_categories'); ?></a>
        <a class="btn btn-secondary btn-sm" href="javascript:;" id="edit-help"
           onclick="document.querySelector('#edit-info').classList.toggle('show')"><i
                    class="<?= ManagerTheme::getStyle('icon_question_circle') ?>"></i>
            <?= ManagerTheme::getLexicon('help'); ?></a>
    </div>
    <p id="edit-info" class="element-edit-message">
        Change category name or delete category from the Manager.
    </p>
    <div class="row">
        <div class="table-responsive">
            <table id="category-edit" class="table data table-even nowrap">
                <thead>
                <tr>
                    <td width="1%"><?= $view->txt('cm_assigned_elements'); ?></td>
                    <td><?= $view->txt('cm_edit_name'); ?></td>
                    <td width="1%"><?= $view->txt('cm_mark_for_deletion'); ?></td>
                    <td width="1%"><?= $view->txt('cm_delete_now'); ?></td>
                </tr>
                </thead>
                <tbody>
                <?php
                $i = 0;
                foreach ($data as $category) : ?>
                    <tr>
                        <td>
                            <button class="btn btn-secondary collapsed" type="button" data-toggle="collapse"
                                    data-target="#collapse-edit-<?= $i; ?>" aria-expanded="false" aria-controls="#collapse-edit-<?= $i; ?>" data-tooltip="#assigned-elements-<?= $category['id']; ?>">
                                <i class="<?= ManagerTheme::getStyle('icon_info_circle') ?>"></i>
                            </button>
                            <div id="assigned-elements-<?= $category['id']; ?>" class="hide"><?php
                                $view->renderView(
                                    'chunks/edit/assigned_elements',
                                    $view->getAllAssignedElements($category['id'])
                                ); ?></div>
                        </td>
                        <td>
                            <input type="hidden" name="<?= $view->get('request_key'); ?>[edit][data][<?= $category['id'] ?>][rank]" value="<?= $category['rank']; ?>"/>
                            <input type="hidden" name="<?= $view->get('request_key'); ?>[edit][data][<?= $category['id'] ?>][origin]" value="<?= urlencode($category['category']); ?>"/>
                            <input type="text" name="<?= $view->get('request_key'); ?>[edit][data][<?= $category['id'] ?>][category]" value="<?= e($category['category']); ?>"/>
                        </td>
                        <td class="text-xs-center">
                            <input type="checkbox" name="<?= $view->get('request_key'); ?>[edit][data][<?= $category['id'] ?>][delete]" value="1"/>
                        </td>
                        <td class="text-xs-center">
                            <a class="btn btn-outline-danger" onclick="return confirm(`<?= $view->txt('are_you_sure'); ?>`);" href="<?= $view->get('url'); ?>&amp;<?= $view->get('request_key'); ?>[delete]=<?= $category['id']; ?>&amp;<?= $view->get('request_key'); ?>[category]=<?= urlencode($category['category']); ?>" data-tooltip="<?= htmlspecialchars($category['category']) ?>::<?= sprintf(
                                $view->txt('cm_delete_element_x_now'),
                                htmlspecialchars($category['category'])
                            ); ?>"><i class="<?= ManagerTheme::getStyle('icon_info_triangle') ?>"></i> <?= $view->txt('delete'); ?></a>
                        </td>
                    </tr>
                    <tr class="collapse" id="collapse-edit-<?= $i; ?>">
                        <td colspan="4">
                            <?php
                            $view->renderView(
                                'chunks/edit/assigned_elements_collapse',
                                $view->getAllAssignedElements($category['id'])
                            ); ?>
                        </td>
                    </tr>
                    <?php
                    $i++; endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</form>
