<form id="category-translation-form" action="<?php
echo $view->get('url'); ?>" method="post">
    <fieldset>
        <legend><?= $view->txt('cm_translate_module_phrases'); ?></legend>
        <table id="category-translation" class="grid" cellpadding="1" cellspacing="1">
            <thead>
            <tr>
                <td class="gridHeader"><?= $view->txt('cm_native_phrase'); ?></td>
                <td class="gridHeader"><?= $view->txt('cm_translation'); ?></td>
            </tr>
            </thead>
            <tbody>
            <?php
            $i = 0;
            foreach ($data as $native => $translation) : ?>
                <tr>
                    <td class="native <?= ($i % 2 === 0) ? 'gridItem' : 'gridAltItem'; ?>">
                        <?= $native; ?>
                    </td>
                    <td class="translation <?= ($i % 2 === 0) ? 'gridItem' : 'gridAltItem'; ?>">
                        <textarea rows="2" cols="80"
                                  name="<?= $view->get('request_key'); ?>[translate][data][<?= urlencode(
                                      $native
                                  ) ?>]"><?= $translation; ?></textarea>
                    </td>
                </tr>
                <?php
                $i++; endforeach; ?>
            </tbody>
            <tfoot>
            <tr>
                <td colspan="4" class="submit">
                    <input type="submit" name="<?= $view->get('request_key'); ?>[translate][submit]"
                           value="<?= $view->txt('cm_translate_phrases'); ?>"/>
                </td>
            </tr>
            </tfoot>
        </table>
    </fieldset>
</form>
