<div class="assigned_elements">
  <?php foreach( $data as $element => $items ) : ?>
  <h5><b><?= $view->txt( $element ); ?></b></h5>
  <?php if( empty( $items ) ) : ?>
  <p class="no_assigned_elements"><?= sprintf( $view->txt('cm_no_x_assigned'), $element ); ?></p>
  <?php else: ?>
  <ul>
    <?php foreach( $items as $item ) : ?>
    <li><?= (strtolower($element)==='templates')? e($item['templatename']) : e($item['name']); ?></li>
    <?php endforeach; ?>
  </ul>
  <?php endif; ?>
  <?php endforeach; ?>
</div>
