<table class="grid">
	<thead>
	<tr>
	<?php foreach( $data as $element => $items ) : ?>
		<td><?= $view->txt( $element ); ?></td>
	<?php endforeach; ?>
	</tr>
	</thead>
	<tbody>
	<tr>
	<?php foreach( $data as $element => $items ) : ?>
		<?php if( empty( $items ) ) : ?>
			<td><p class="no_assigned_elements"><?= $view->txt( 'none' ); ?></p></td>
		<?php else: ?>
			<td>
				<ul>
				<?php foreach( $items as $item ) : ?>
					<li><?= (strtolower($element)==='templates')? e($item['templatename']) : e($item['name']); ?></li>
				<?php endforeach; ?>
				</ul>
			</td>
		<?php endif; ?>
	<?php endforeach; ?>
	</tr>
	</tbody>
</table>
