<?php
if( ! defined('IN_MANAGER_MODE') || IN_MANAGER_MODE !== true) {
    die("<b>INCLUDE_ORDERING_ERROR</b><br /><br />Please use the EVO Content Manager instead of accessing this file directly.");
}
?>

<div class="sectionHeader"><?php echo $_lang['documentation']; ?></div><div class="sectionBody">
    <table border="0" cellspacing="0" cellpadding="0">
        <tr><td><a href="https://github.com/evocms-community/docs" target="_blank">What is EVO?</a></td><td></td><td>Official EVO documentation</td></tr>
        <tr><td><a href="https://evocms.ru/" target="_blank">evocms.ru</a></td><td></td><td>Home of EVO</td></tr>
        <tr><td><a href="https://t.me/evo_cms" target="_blank">EVO Telegram Group</a></td><td></td><td>General support & discussions</td></tr>
        <tr><td><a href="http://docs.evolution-cms.com/" target="_blank">docs.evolution-cms.com</a></td><td><a href="https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=http://docs.evolution-cms.com/" target="_blank">Google Translate</a></td><td>Further documentation</td></tr>
        <tr><td><a href="http://saniock.com/modx-evolution/developer/api.html" target="_blank">API Reference</a></td><td><a href="https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=http://saniock.com/modx-evolution/developer/api.html" target="_blank">Google Translate</a></td><td>Further documentation</td></tr>
        <tr><td><a href="https://modx.evo.im/" target="_blank">MODX.im</a></td><td><a href="https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=http://modx.im/" target="_blank">Google Translate</a></td><td>Old russian community site</td></tr>
    </table>
</div>

